=== sambacha/yearn-vault-schema/archive/dep_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "symbol": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "vaultSymbol": {
            "type": "string"
        },
        "erc20address": {
            "type": "string"
        },
        "vaultContractAddress": {
            "type": "string"
        },
        "vaultContractABI": {
            "type": "string"
        },
        "balance": {
            "type": "integer"
        },
        "vaultBalance": {
            "type": "integer"
        },
        "decimals": {
            "type": "integer"
        },
        "deposit": {
            "type": "boolean"
        },
        "depositAll": {
            "type": "boolean"
        },
        "withdraw": {
            "type": "boolean"
        },
        "withdrawAll": {
            "type": "boolean"
        },
        "lastMeasurement": {
            "type": "integer"
        },
        "measurement": {
            "type": "integer"
        }
    },
    "required": [
        "id",
        "name",
        "symbol",
        "description",
        "vaultSymbol",
        "erc20address",
        "vaultContractAddress",
        "vaultContractABI",
        "balance",
        "vaultBalance",
        "decimals",
        "deposit",
        "depositAll",
        "withdraw",
        "withdrawAll",
        "lastMeasurement",
        "measurement"
    ]
}

=== sambacha/yearn-vault-schema/vault.json
{
    "id": "ETH",
    "name": "ETH",
    "symbol": "ETH",
    "description": "Ether",
    "vaultSymbol": "yETH",
    "erc20address": "Ethereum",
    "vaultContractAddress": "0xe1237aA7f535b0CC33Fd973D66cBf830354D16c7",
    "vaultContractABI": "config.vaultContractV4ABI",
    "balance": 0,
    "vaultBalance": 0,
    "decimals": 18,
    "deposit": true,
    "depositAll": false,
    "withdraw": true,
    "withdrawAll": true,
    "lastMeasurement": 10774489,
    "measurement": 1000000000000000000
}
